package diom_models

// This file is @generated DO NOT EDIT

type SvixPollerCreateIn struct {
	Namespace *string `msgpack:"namespace,omitempty"`
	// The topic that polled webhooks will be written too. If the topic does not exist,
	// a new topic will be created automatically.
	Topic    string `msgpack:"topic"`
	PollerId string `msgpack:"poller_id"` // A user chosen unique identifier for the Poller.
	Token    string `msgpack:"token"`     // The AutoConfig token generated by Svix.
}
