disallowed-types = [
    { path = "axum::Json", replacement = "coyote_proto::MsgPackOrJson" },
    { path = "serde_json::Value", reason = "not compatible with msgpack" },
]

disallowed-methods = [
    { path = "jiff::Timestamp::now", reason = "generally, should be reading cluster Monotime" },
    { path = "tokio::task::spawn_blocking", replacement = "coyote_core::task::spawn_blocking_in_current_span", reason = "tokio::task::spawn_blocking loses tracing span information" }
]
