repos:
  - repo: builtin
    hooks:
      - id: end-of-file-fixer
        # temporarily exclude some SDKs, needs openapi-codegen fix
        exclude: "(^.yarn/)|(.svg$)|(^z-clients/javascript)|(^z-clients/java)"
      - id: trailing-whitespace
        # temporarily exclude some SDKs, needs auto-formatting
        exclude: "(^.yarn/)|(.svg$)|(^z-clients/javascript)|(^z-clients/java)"
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: "^infra/helm"
      - id: check-json
        exclude: "(tsconfig|foo).json$"
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        exclude: "^infra/helm"
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/crate-ci/typos
    rev: v1.45.0
    hooks:
      - id: typos
