listen_address = "0.0.0.0:8050"
log_level="info"
environment = "dev"

opentelemetry_metrics_use_http=true
opentelemetry_service_name="coyote"
opentelemetry_address="http://localhost:4317"
opentelemetry_metrics_address="http://localhost:9090/api/v1/otlp/v1/metrics"
opentelemetry_sample_ratio=0.1

[cluster]
log_sync_interval_commits = 0
log_sync_interval_ms = 10
log_ack_immediately = false
