package diom

// This file is @generated DO NOT EDIT

import diom_models "github.com/svix/diom/clients/go/internal/models"

type (
	CacheCreateNamespaceIn        = diom_models.CacheCreateNamespaceIn
	CacheCreateNamespaceOut       = diom_models.CacheCreateNamespaceOut
	CacheDeleteIn                 = diom_models.CacheDeleteIn
	CacheDeleteOut                = diom_models.CacheDeleteOut
	CacheGetIn                    = diom_models.CacheGetIn
	CacheGetNamespaceIn           = diom_models.CacheGetNamespaceIn
	CacheGetNamespaceOut          = diom_models.CacheGetNamespaceOut
	CacheGetOut                   = diom_models.CacheGetOut
	CacheSetIn                    = diom_models.CacheSetIn
	CacheSetOut                   = diom_models.CacheSetOut
	Consistency                   = diom_models.Consistency
	EvictionPolicy                = diom_models.EvictionPolicy
	IdempotencyAbortIn            = diom_models.IdempotencyAbortIn
	IdempotencyAbortOut           = diom_models.IdempotencyAbortOut
	IdempotencyCreateNamespaceIn  = diom_models.IdempotencyCreateNamespaceIn
	IdempotencyCreateNamespaceOut = diom_models.IdempotencyCreateNamespaceOut
	IdempotencyGetNamespaceIn     = diom_models.IdempotencyGetNamespaceIn
	IdempotencyGetNamespaceOut    = diom_models.IdempotencyGetNamespaceOut
	KvCreateNamespaceIn           = diom_models.KvCreateNamespaceIn
	KvCreateNamespaceOut          = diom_models.KvCreateNamespaceOut
	KvDeleteIn                    = diom_models.KvDeleteIn
	KvDeleteOut                   = diom_models.KvDeleteOut
	KvGetIn                       = diom_models.KvGetIn
	KvGetNamespaceIn              = diom_models.KvGetNamespaceIn
	KvGetNamespaceOut             = diom_models.KvGetNamespaceOut
	KvGetOut                      = diom_models.KvGetOut
	KvSetIn                       = diom_models.KvSetIn
	KvSetOut                      = diom_models.KvSetOut
	MsgIn                         = diom_models.MsgIn
	MsgNamespaceCreateIn          = diom_models.MsgNamespaceCreateIn
	MsgNamespaceCreateOut         = diom_models.MsgNamespaceCreateOut
	MsgNamespaceGetIn             = diom_models.MsgNamespaceGetIn
	MsgNamespaceGetOut            = diom_models.MsgNamespaceGetOut
	MsgPublishIn                  = diom_models.MsgPublishIn
	MsgPublishOut                 = diom_models.MsgPublishOut
	MsgPublishOutTopic            = diom_models.MsgPublishOutTopic
	MsgQueueAckIn                 = diom_models.MsgQueueAckIn
	MsgQueueAckOut                = diom_models.MsgQueueAckOut
	MsgQueueConfigureIn           = diom_models.MsgQueueConfigureIn
	MsgQueueConfigureOut          = diom_models.MsgQueueConfigureOut
	MsgQueueNackIn                = diom_models.MsgQueueNackIn
	MsgQueueNackOut               = diom_models.MsgQueueNackOut
	MsgQueueReceiveIn             = diom_models.MsgQueueReceiveIn
	MsgQueueReceiveOut            = diom_models.MsgQueueReceiveOut
	MsgQueueRedriveDlqIn          = diom_models.MsgQueueRedriveDlqIn
	MsgQueueRedriveDlqOut         = diom_models.MsgQueueRedriveDlqOut
	MsgStreamCommitIn             = diom_models.MsgStreamCommitIn
	MsgStreamCommitOut            = diom_models.MsgStreamCommitOut
	MsgStreamReceiveIn            = diom_models.MsgStreamReceiveIn
	MsgStreamReceiveOut           = diom_models.MsgStreamReceiveOut
	MsgStreamSeekIn               = diom_models.MsgStreamSeekIn
	MsgStreamSeekOut              = diom_models.MsgStreamSeekOut
	MsgTopicConfigureIn           = diom_models.MsgTopicConfigureIn
	MsgTopicConfigureOut          = diom_models.MsgTopicConfigureOut
	OperationBehavior             = diom_models.OperationBehavior
	PingOut                       = diom_models.PingOut
	QueueMsgOut                   = diom_models.QueueMsgOut
	RateLimitStatus               = diom_models.RateLimitStatus
	RateLimiterCheckIn            = diom_models.RateLimiterCheckIn
	RateLimiterCheckOut           = diom_models.RateLimiterCheckOut
	RateLimiterCreateNamespaceIn  = diom_models.RateLimiterCreateNamespaceIn
	RateLimiterCreateNamespaceOut = diom_models.RateLimiterCreateNamespaceOut
	RateLimiterFixedWindowConfig  = diom_models.RateLimiterFixedWindowConfig
	RateLimiterGetNamespaceIn     = diom_models.RateLimiterGetNamespaceIn
	RateLimiterGetNamespaceOut    = diom_models.RateLimiterGetNamespaceOut
	RateLimiterGetRemainingIn     = diom_models.RateLimiterGetRemainingIn
	RateLimiterGetRemainingOut    = diom_models.RateLimiterGetRemainingOut
	RateLimiterTokenBucketConfig  = diom_models.RateLimiterTokenBucketConfig
	Retention                     = diom_models.Retention
	StorageType                   = diom_models.StorageType
	StreamMsgOut                  = diom_models.StreamMsgOut
)
