crds:
  enabled: true
  upgrade:
    enabled: true
    forceConflicts: true

operator:
  nodeSelector:
    db-name: diom
  tolerations:
    - key: db-name
      operator: Equal
      value: diom
      effect: NoSchedule

cluster:
  image:
    tag: ""
  spec:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-attributes: dns_record.client_routing_policy=availability_zone_affinity
        external-dns.alpha.kubernetes.io/hostname: "diom.svix.local"
    storage:
      persistent:
        size: 64Gi
        storageClass: gp3-encrypted
    envVar:
      - name: DIOM_OPENTELEMETRY_METRICS_ADDRESS
        value: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090/api/v1/otlp/v1/metrics"
      - name: DIOM_OPENTELEMETRY_METRICS_USE_HTTP
        value: "true"
      - name: DIOM_LOG_LEVEL
        value: debug
      - name: RUST_BACKTRACE
        value: "1"
      - name: DIOM_LOG_FORMAT
        value: "json"
      - name: DIOM_OPENTELEMETRY_ADDRESS
        value: grpc://datadog-agent.datadog.svc.cluster.local:4317
    nodeSelector:
      db-name: diom
    tolerations:
      - key: db-name
        operator: Equal
        value: diom
        effect: NoSchedule
    adminToken:
        valueFrom:
          secretKeyRef:
            name: diom-admin-token
            key: DIOM_ADMIN_TOKEN
