crds:
  enabled: true
  upgrade:
    enabled: true
    forceConflicts: true

operator:
  nodeSelector:
    db-name: diom
  tolerations:
    - key: db-name
      operator: Equal
      value: diom
      effect: NoSchedule

cluster:
  image:
    tag: ""
  spec:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-attributes: dns_record.client_routing_policy=availability_zone_affinity
        external-dns.alpha.kubernetes.io/hostname: "diom.svix.local"
    storage:
      persistent:
        size: 64Gi
        storageClass: gp3-encrypted
    logLevel: debug
    logFormat: json
    opentelemetryAddress: grpc://datadog-agent.datadog.svc.cluster.local:4317
    opentelemetryMetricsAddress: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090/api/v1/otlp/v1/metrics"
    opentelemetryMetricsUseHttp: true
    envVar:
      - name: RUST_BACKTRACE
        value: "1"
    nodeSelector:
      db-name: diom
    tolerations:
      - key: db-name
        operator: Equal
        value: diom
        effect: NoSchedule
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                diom.svix.com/cluster: diom
          - topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchLabels:
                diom.svix.com/cluster: diom
    adminToken:
      value: "admin_abcdefghijlmnopqrstuvwxyz012345"
