apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coyote
  namespace: coyote
  annotations:
    tailscale.com/hostname: coyote-dev-euw1
    tailscale.com/tags: "tag:k8s-dev"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coyote
                port:
                  number: 8080
