// this file is @generated

export interface SvixPollerCreateIn {
    namespace?: string | null;
    /**
     * The topic that polled webhooks will be written too. If the topic does not exist,
     * a new topic will be created automatically.
     */
    topic: string;
    /** A user chosen unique identifier for the Poller. */
    pollerId: string;
    /** The AutoConfig token generated by Svix. */
    token: string;
}

export const SvixPollerCreateInSerializer = {
    // biome-ignore lint/suspicious/noExplicitAny: intentional any
    _fromJsonObject(object: any): SvixPollerCreateIn {
        return {
            namespace: object['namespace'],
            topic: object['topic'],
            pollerId: object['poller_id'],
            token: object['token'],
        };
    },

    // biome-ignore lint/suspicious/noExplicitAny: intentional any
    _toJsonObject(self: SvixPollerCreateIn): any {
        return {
            'namespace': self.namespace,
            'topic': self.topic,
            'poller_id': self.pollerId,
            'token': self.token,
        };
    }
}