# this file is @generated

from ..internal.base_model import BaseModel


class SvixPollerCreateIn(BaseModel):
    namespace: str | None = None

    topic: str
    """The topic that polled webhooks will be written too. If the topic does not exist,
    a new topic will be created automatically."""

    poller_id: str
    """A user chosen unique identifier for the Poller."""

    token: str
    """The AutoConfig token generated by Svix."""
