listen_address = "127.0.0.1:8052"
jwt_secret = "insecure_cluster"
jwt_algorithm = "HS256"
environment = "dev"
persistent_db.path = "./db-third/persistent"
ephemeral_db.path = "./db-third/ephemeral"
opentelemetry_address = "http://localhost:4317"
opentelemetry_metrics_address = "http://localhost:9090/api/v1/otlp/v1/metrics"
opentelemetry_metrics_use_http = true

[cluster]
secret = "hunter2"
listen_address = "127.0.0.1:18052"
name = "three-node-cluster"
seed_nodes = ["127.0.0.1:18050", "127.0.0.1:18051", "127.0.0.1:18052"]
auto_initialize = false
