// this file is @generated
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SvixPollerCreateIn {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,

    /// The topic that polled webhooks will be written too. If the topic does not exist,
    /// a new topic will be created automatically.
    pub topic: String,

    /// A user chosen unique identifier for the Poller.
    pub poller_id: String,

    /// The AutoConfig token generated by Svix.
    pub token: String,
}

impl SvixPollerCreateIn {
    pub fn new(topic: String, poller_id: String, token: String) -> Self {
        Self {
            namespace: None,
            topic,
            poller_id,
            token,
        }
    }

    pub fn with_namespace(mut self, value: impl Into<Option<String>>) -> Self {
        self.namespace = value.into();
        self
    }
}
