name: Diom CI

on:
  workflow_dispatch:
  workflow_call:

env:
  # Keep this in sync with server/ee.Dockerfile
  ci_toolchain_rust: "1.98.1"

jobs:
  benchmark:
    name: Benchmark
    timeout-minutes: 15
    runs-on: ubicloud-standard-8-ubuntu-2404
    defaults:
      run:
        working-directory: ./benchmarks
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # v1
        with:
          toolchain: ${{ env.ci_toolchain_rust }}
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          # include relevant information in the cache name
          prefix-key: "benchmarks-${{ env.ci_toolchain_rust }}"
      - name: Install cargo-criterion
        run: cargo install cargo-criterion
      - name: Run benchmarks
        # For some weird reason, it seems to log test output
        # to stderr:
        run: cargo criterion --output-format bencher 2>&1 | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v6.1.0
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@4322e5726e6334590d251fc4f92bec0efafc45dc # v1.22.2
        with:
          tool: 'cargo'
          output-file-path: ./benchmarks/output.txt
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          fail-on-alert: true
