name: Diom CI
on:
  workflow_dispatch:
  workflow_call:
# When pushing to a PR, cancel any jobs still running for the previous head commit of the PR
concurrency:
  # head_ref is only defined for pull requests, run_id is always unique and defined so if this
  # workflow was not triggered by a pull request, nothing gets cancelled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
jobs:
  check-fmt:
    name: Formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: taiki-e/install-action@cargo-sort
      - run: cargo fmt -- --check
      - run: cargo sort --check --workspace -o package,lib,bin,features,dependencies,dev-dependencies,lints,workspace
  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      # Use beta toolchain for a middle ground between effective caching and the latest lints
      - uses: dtolnay/rust-toolchain@beta
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          # only save the cache on the main branch
          # cf https://github.com/Swatinem/rust-cache/issues/95
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - run: cargo clippy --workspace --all-features --all-targets
  # TODO: re-enable cargo-machete when we're further along in dev
  # check-unused-deps:
  #   name: Check Unused Dependencies
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: taiki-e/install-action@cargo-machete
  #     - run: cargo machete
  pre-commit:
    name: Validate pre-commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - uses: pre-commit/action@v3.0.1
  test:
    name: Test
    runs-on: ubuntu-24.04
    env:
      RUST_LOG: debug
      "DIOM:LOG_LEVEL": debug
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-nextest
      - uses: taiki-e/install-action@just
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - run: just test --profile ci
  check-codegen:
    name: Check openapi.json and SDK freshness
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Regerate openapi.json and SDKs
        run: cargo codegen
      - name: Check for uncommitted changes
        run: |
          gs=$(git status -s)
          if [[ -n "$gs" ]]; then
            echo 'there are uncommitted changes!'
            # `cargo codegen` is not meant to be executed here 😒
            # shellcheck disable=SC2016
            echo 'please rerun `cargo codegen` and commit the result'
            git status
            exit 1
          else
            echo 'all good.'
          fi
