name: Clients

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint-js:
    name: Lint JavaScript
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: clients/javascript
    steps:
      - uses: actions/checkout@v6
      - id: changed-files
        uses: tj-actions/changed-files@v47.0.4
        with:
          files: "clients/javascript"
      - run: npm ci
        if: steps.changed-files.outputs.test_any_changed == 'true'
      - run: npm run lint
        if: steps.changed-files.outputs.test_any_changed == 'true'
      - run: |
          echo "succeed even if we skipped linting"
          exit 0

  lint-python:
    name: Lint Python
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - id: changed-files
        uses: tj-actions/changed-files@v47.0.4
        with:
          files: "clients/python"
      - name: Install uv
        if: steps.changed-files.outputs.test_any_changed == 'true'
        uses: astral-sh/setup-uv@v7
      - run: uv run --only-dev ruff check coyote
        if: steps.changed-files.outputs.test_any_changed == 'true'
        working-directory: clients/python
      - run: |
          echo "succeed even if we skipped linting"
          exit 0
