name: Docker Build Release

on:
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
      version:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: ./Dockerfile
      target:
        required: false
        type: string
        default: prod
      context:
        required: false
        type: string
        default: .
      dry_run:
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  extract-secrets:
    # reusable workflows can't be invoked in an environment, so we need to run this step
    # in the environment, extract the credentials, and then pass them in as inputs to the other
    # job
    runs-on: ubuntu-latest
    environment: release
    steps:
      - run: echo "no-op"
    outputs:
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:
    needs: [extract-secrets]
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    with:
      output: image
      file: ${{ inputs.dockerfile }}
      context: ${{ inputs.context }}
      target: ${{ inputs.target }}
      push: ${{ inputs.dry_run != true }}
      platforms: linux/amd64,linux/arm64
      meta-images: ${{ inputs.image_repo }}
      meta-tags: |
        type=ref,event=tag
        type=semver,pattern={{version}},value=${{inputs.version}}
        type=semver,pattern={{major}},value=${{inputs.version}}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ needs.extract-secrets.outputs.docker-username }}
          username: ${{ needs.extract-secrets.outputs.docker-password }}
