name: Helm Publish to GHCR

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false
      dry_run:
        type: boolean
        default: false

jobs:
  helm-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mangle charts for private deploys
        if: ${{ !inputs.is_release }}
        run: |
          # Change image repositories
          yq -i '.name = "diom-private"' infra/helm-diom/Chart.yaml
          yq -i '.operator.image.repository = "ghcr.io/svix/diom-operator-private"' infra/helm-diom/values.yaml
          yq -i '.cluster.image.repository = "ghcr.io/svix/diom-server-private"' infra/helm-diom/values.yaml

          # Change image tags
          yq -i '.cluster.image.tag = "sha-${{ github.sha }}"' infra/helm-diom/values.yaml
          yq -i '.operator.image.tag = "sha-${{ github.sha }}"' infra/helm-diom/values.yaml

          helm package ./infra/helm-diom --version "0.0.0-${{ github.sha }}"

      - name: Package release chart
        if: ${{ inputs.is_release }}
        run: |
          helm package ./infra/helm-diom

      - name: Push chart
        if: ${{ !inputs.dry_run }}
        run: helm push diom*.tgz oci://ghcr.io/svix/charts
