name: Helm Publish to GHCR

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        description: 'Override the version specified in Chart.yaml (only used for private deployments)'
      operator_image_tag:
        required: true
        type: string
      server_image_tag:
        required: true
        type: string
      is_release:
        type: boolean
        default: false
      dry_run:
        type: boolean

jobs:
  helm-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        run: |
          yq -i '.cluster.image.tag = "${{ inputs.server_image_tag }}"' infra/helm-diom/values.yaml
          yq -i '.operator.image.tag = "${{ inputs.operator_image_tag }}"' infra/helm-diom/values.yaml

      - name: Mangle charts for private deploys
        if: ${{ !inputs.is_release }}
        run: |
          yq -i '.name = "diom-private"' infra/helm-diom/Chart.yaml
          yq -i '.operator.image.repository = "ghcr.io/svix/diom-operator"' infra/helm-diom/values.yaml
          yq -i '.cluster.image.repository = "ghcr.io/svix/diom-server"' infra/helm-diom/values.yaml

      - name: Package chart
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            helm package ./infra/helm-diom --version ${{ inputs.version }}
          else
            helm package ./infra/helm-diom
          fi

      - name: Push chart
        if: ${{ !inputs.dry_run }}
        run: helm push diom*.tgz oci://ghcr.io/svix/charts
