name: Helm Publish to GHCR

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false
      dry_run:
        type: boolean
        default: false

jobs:
  helm-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Login to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mangle charts for private deploys
        if: ${{ !inputs.is_release }}
        run: |
          # Change image repositories
          yq -i '.name = "diom-private"' infra/helm-diom/Chart.yaml
          yq -i '.operator.image.repository = "ghcr.io/svix/diom-operator-private"' infra/helm-diom/values.yaml
          yq -i '.cluster.image.repository = "ghcr.io/svix/diom-server-private"' infra/helm-diom/values.yaml

          # Change image tags
          yq -i '.cluster.image.tag = "sha-${{ github.sha }}"' infra/helm-diom/values.yaml
          yq -i '.operator.image.tag = "sha-${{ github.sha }}"' infra/helm-diom/values.yaml

          helm package ./infra/helm-diom --version "0.0.0-${{ github.sha }}"

      - name: Package release chart
        if: ${{ inputs.is_release }}
        run: |
          helm package ./infra/helm-diom

      - name: Push chart
        if: ${{ !inputs.dry_run }}
        run: helm push diom*.tgz oci://ghcr.io/svix/charts
