name: JavaScript Release

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: release

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Install modules
        working-directory: z-clients/javascript
        run: npm install

      - name: Publish
        working-directory: z-clients/javascript
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
