name: Java

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Java SDK
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: clients/java
    steps:
      - uses: actions/checkout@v6
      - run: ./gradlew build
