name: JavaScript

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint-js:
    name: Lint JavaScript
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: z-clients/javascript
    steps:
      - uses: actions/checkout@v6
      - run: npm ci
      - run: npm run lint
      - run: npm run build
