name: Lint OpenAPI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - '.github/workflows/lint-openapi.yml'
      - 'openapi.json'

jobs:
  lint-openapi:
    name: Lint openapi.json
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: pb33f/vacuum-action@v2
        with:
          openapi_path: openapi.json
          ruleset: .vacuum.yaml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # raise this as time goes on and we fix some stuff
          minimum_score: 0
