name: Mega Releaser

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  packages: write # to stage stuff in GHCR

jobs:
  docker:
    uses: ./.github/workflows/docker-release.yml
    with:
      dry_run: false
    secrets: inherit

  java:
    uses: ./.github/workflows/java-release.yml
    secrets: inherit

  javascript:
    uses: ./.github/workflows/javascript-release.yml
    secrets: inherit

  # See commit message, Python trusted publishing is broken with sub workflows
  # python:
  #  uses: ./.github/workflows/python-release.yml

  rust:
    uses: ./.github/workflows/rust-release.yml
    secrets: inherit
