name: CI on Push to Main
on:
  push:
    branches: ['main']
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  benchmark:
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
  docker_publish:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    permissions:
      actions: read
      packages: write
      security-events: write
