name: CI on Push to Main

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  # Disabling for now because results are too inconsistent
  # on github runners. Will revisit later.
  #  benchmark:
  #    uses: ./.github/workflows/benchmark.yml
  #    secrets: inherit

  java:
    uses: ./.github/workflows/java.yml

  javascript:
    uses: ./.github/workflows/javascript.yml

  python:
    uses: ./.github/workflows/python.yml

  docker_publish_server:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    needs: ci
    with:
      image_name: svix/diom-server-private
      target: prod
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write

  docker_publish_cli:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    needs: ci
    with:
      image_name: svix/diom-cli-private
      target: cli-prod
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write

  docker_publish_operator:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    needs: ci
    with:
      image_name: svix/diom-operator-private
      target: prod
      file: ./infra/operator/Dockerfile
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write

  helm-publish:
    needs: ci
    uses: ./.github/workflows/helm-publish.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      version: 0.0.0-${{ github.sha }}
      server_image_tag: sha-${{ github.sha }}
      operator_image_tag: sha-${{ github.sha }}
      is_release: false

  staging-deploy:
    needs: [docker_publish_operator, docker_publish_server, helm-publish]
    runs-on: ubuntu-24.04
    environment: diom-staging-deploy
    steps:
      - name: Dispatch deploy to diom-staging
        run: |
          gh api repos/svix/diom-staging/dispatches --method POST --input - <<EOF
          {"event_type":"deploy-staging","client_payload":{"chart_version":"0.0.0-${GITHUB_SHA}"}}
          EOF
        env:
          GH_TOKEN: ${{ secrets.STAGING_DISPATCH_PAT }}
