name: CI on Push to Main
on:
  push:
    branches: ['main']
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    # Disabling for now because results are too inconsistent
    # on github runners. Will revisit later.
    #  benchmark:
    #    uses: ./.github/workflows/benchmark.yml
    #    secrets: inherit
  docker_publish_server:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    needs: ci
    with:
      image_name: svix/diom-server
      target: prod
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write
  docker_publish_cli:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    needs: ci
    with:
      image_name: svix/diom-cli
      target: cli-prod
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write
  docker_publish_operator:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    needs: ci
    with:
      image_name: svix/diom-operator
      target: prod
      context: ./infra/operator
      file: ./infra/operator/Dockerfile
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write
