name: Python

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: z-clients/python
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      - run: uv run --only-dev ruff check
      - run: uv run pyrefly check
